#!/usr/bin/env bash
# configurea Ubuntu machine with Ngin-X
sudo apt-get update
sudo apt-get install nginx -y
echo 'Holberton School' | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx restart