#!/usr/bin/env bash
# configurea Ubuntu machine with Ngin-X
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start