#!/usr/bin/env bash
# configurea Ubuntu machine with Ngin-X
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo echo 'Holberton School' > /var/www/html/index.html
sudo service nginx start
