#!/usr/bin/env bash
# Script to install and configure HAproxy
sudo apt-get -y update
# Install HA Proxy
sudo apt-get -y install haproxy
# Enable to HA Proxy to start at boot
sudo echo "ENABLED=1" >> /etc/default/haproxy

sudo echo "
frontend web-frontend
	bind *:80
	mode http
	default_backend web-backend
 backend web-backend
	balance roundrobin
	server 1865-web-01 35.229.79.81:80 check
	server 1865-web-02 35.231.187.197:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
